version: '3'

networks:
    laravel:
        driver: bridge

services:
    postgres:
        image: postgres
        restart: always
        environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=mydb
        ports:
        - "5436:5432"
        volumes:
        - ./postgres/data:/var/lib/postgresql/data
        networks:
            - laravel

    mongodb:
        image: mongo:latest
        restart: always
        environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
        - "27017:27017"
        volumes:
        - ./mongodb/data:/data/db
        networks:
            - laravel

    nginx:
        image: nginx
        restart: always
        ports:
        - "8080:80"
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/html:/usr/share/nginx/html
        networks:
            - laravel

    apache:
        image: httpd
        restart: always
        ports:
        - "85:80"
        volumes:
        - ./apache/html:/var/www/html
        networks:
            - laravel

    laravel:
        build:
            context: laravel
            dockerfile: Dockerfile
        restart: always
        environment:
            - COMPOSER_HOME=app/composer
            - COMPOSER_CACHE_DIR=app/composer/cache
        volumes:
            - ./laravel:/var/www
        depends_on:
            - postgres
        networks:
            - laravel

    vue:
        build:
        context: ./vue
        target: development
        restart: always
        ports:
        - "5173:5173"
        volumes:
        - ./vue:/app
        - /app/node_modules
        networks:
        - laravel
        environment:
        - VITE_API_BASE_URL=http://laravel:8000/api
        - CHOKIDAR_USEPOLLING=true

