version: '3'

services:
    postgres:
        image: postgres
        restart: always
        environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=mydb
        ports:
        - "5436:5432"
        volumes:
        - ./postgres/data:/var/lib/postgresql/data

    mongodb:
        image: mongo:latest
        restart: always
        environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
        - "27017:27017"
        volumes:
        - ./mongodb/data:/data/db

